default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  host: ec2-23-21-160-38.compute-1.amazonaws.com
  database: d7kg526oh1setb
  username: nbkmbhfqndjqff
  password: 37d097ab668f3e99b30e4f4f117915b871ccc82a630b08f499174e6bed1643cc